# Generated by Django 4.0.5 on 2022-08-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('items_used', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('calories', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('produce_type', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(related_name='catergory', to='food.category')),
                ('recipes', models.ManyToManyField(related_name='Recipes', to='food.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='recipes',
            field=models.ManyToManyField(related_name='recipes', to='food.recipe'),
        ),
    ]
