# Generated by Django 4.1 on 2022-08-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catergory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=50)),
                ("calories", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=50)),
                ("produce_type", models.CharField(max_length=50)),
                ("name", models.CharField(default=0, max_length=500)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="catergory", to="food.catergory"
                    ),
                ),
                (
                    "recipes",
                    models.ManyToManyField(related_name="Recipes", to="food.recipe"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="catergory",
            name="recipes",
            field=models.ManyToManyField(related_name="category", to="food.recipe"),
        ),
    ]
